
export const getCoinIconURL = (coinTicker) => {
    const coinIconMap = {
        "???": "https://i.pinimg.com/originals/0e/a9/7e/0ea97e89712c98fa1d7127d81f07bc4a.png",
        "ETH": "https://ethereum.org/static/a183661dd70e0e5c70689a0ec95ef0ba/16c7d/eth-diamond-purple.png",
        "WETH": "https://aave.com/static/media/weth.3502a1ea.svg",
        "USDC": "https://aave.com/static/media/usdc.8dd9681c.svg",
        "USDT": "https://aave.com/static/media/usdt.49e25172.svg",
        "TUSD": "",
        "sUSD": "",
        "BUSD": "",
        "GUSD": "",
        "DAI": "https://aave.com/static/media/dai.59d423e0.svg",
        "AAVE": "https://aave.com/static/media/aave.aadf289d.svg",
        "UNI": "https://aave.com/static/media/uni.aacd4d79.svg",
        "YFI": "https://aave.com/static/media/yfi.1c24d18a.svg",
        "BAT": "",
        "REN": "",
        "ENJ": "",
        "KNC": "",
        "LINK": "https://aave.com/static/media/link.83c397b4.svg",
        "MANA": "",
        "MKR": "",
        "SNX": "https://aave.com/static/media/snx.c2239fb6.svg",
        "WBTC": "https://aave.com/static/media/wbtc.f524516c.svg",
        "ZRX": "",
        "CRV": "",

        "COMP": "",
        "SUSHI": "",
        "1INCH": "",
        "BAO": "",
        "ALPHA": "",
        "CREAM": "",
        "PICKLE": "",
        "RSR": "",
        "RUNE": "",
        "UMA": "",
        "NXM": "",
        "BAL": "",
        "BAND": "",
        "HEGIC": "",
        "MIR": "",
        "DPI": "",
        "FARM": "",
        "BADGER": "",
        "DIGG": "",
        "SFI": "",
        "AKRO": "",
        "BOND": "",

        "GRT": "",
        "ESD": "",
        "DSD": "",
        "FRAX": "",
    }

    return coinIconMap.hasOwnProperty(coinTicker) ? coinIconMap[coinTicker] : coinIconMap["???"]
}
