
export const getCoinIconURL = (coinTicker) => {
    const coinIconMap = {
        "???": "https://www.freepnglogos.com/uploads/thinking-png/thinking-speaking-emoji-draper-inc-blog-site-4.png",
        "ETH": "https://ethereum.org/static/a183661dd70e0e5c70689a0ec95ef0ba/16c7d/eth-diamond-purple.png",
        "aETH": "https://aave.com/static/media/aETH.6f2c0bbe.svg",
        "WETH": "https://aave.com/static/media/weth.3502a1ea.svg",
        "aWETH": "https://aave.com/static/media/aWETH.8bcd3ba4.svg",
        "USDC": "https://aave.com/static/media/usdc.8dd9681c.svg",
        "aUSDC": "https://aave.com/static/media/aUSDC.e260d492.svg",
        "USDT": "https://aave.com/static/media/usdt.49e25172.svg",
        "aUSDT": "https://aave.com/static/media/aUSDT.78f5faae.svg",
        "TUSD": "https://aave.com/static/media/tusd.a9e1a2e9.svg",
        "aTUSD":"https://aave.com/static/media/aTUSD.08592b49.svg",
        "sUSD": "https://aave.com/static/media/susd.f14c0307.svg",
        "aSUSD": "https://aave.com/static/media/aSUSD.9b00ffc6.svg",
        "BUSD": "https://aave.com/static/media/busd.24a05a4a.svg",
        "aBUSD": "https://aave.com/static/media/aBUSD.346a65d7.svg",
        "GUSD": "https://aave.com/static/media/gusd.a1f70ee3.svg",
        "aGUSD": "",
        "DAI": "https://aave.com/static/media/dai.59d423e0.svg",
        "aDAI": "https://aave.com/static/media/aDAI.84b6c41f.svg",
        "AAVE": "https://aave.com/static/media/aave.aadf289d.svg",
        "aAAVE": "",
        "UNI": "https://aave.com/static/media/uni.aacd4d79.svg",
        "aUNI": "https://aave.com/static/media/aUNI.81ed9562.svg",
        "YFI": "https://aave.com/static/media/yfi.1c24d18a.svg",
        "aYFI": "https://aave.com/static/media/aYFI.15777dd9.svg",
        "BAT": "https://aave.com/static/media/bat.b277f0a1.svg",
        "aBAT": "",
        "REN": "https://aave.com/static/media/ren.2bd894ce.svg",
        "aREN": "",
        "ENJ": "https://aave.com/static/media/enj.461dbbb9.svg",
        "aENJ": "",
        "KNC": "https://aave.com/static/media/knc.35b14575.svg",
        "aKNC": "",
        "REP": "",
        "aREP": "",
        "LINK": "https://aave.com/static/media/link.83c397b4.svg",
        "aLINK": "https://aave.com/static/media/aLINK.412c6589.svg",
        "MANA": "https://aave.com/static/media/mana.7a12a13f.svg",
        "aMANA": "https://aave.com/static/media/aMANA.f89a1098.svg",
        "MKR": "https://aave.com/static/media/mkr.bfdf58ed.svg",
        "aMKR": "https://aave.com/static/media/aMKR.ac965178.svg",
        "SNX": "https://aave.com/static/media/snx.c2239fb6.svg",
        "aSNX": "https://aave.com/static/media/aSNX.3238f3e7.svg",
        "WBTC": "https://aave.com/static/media/wbtc.f524516c.svg",
        "aWBTC": "https://aave.com/static/media/aWBTC.41453c2a.svg",
        "ZRX": "https://aave.com/static/media/zrx.3cffa8ed.svg",
        "aZRX": "https://aave.com/static/media/aZRX.9be555a9.svg",
        "CRV": "https://aave.com/static/media/crv.afc0d649.svg",
        "aCRV": "https://aave.com/static/media/aCRV.a49c7255.svg",
        "COMP": "https://s2.coinmarketcap.com/static/img/coins/64x64/5692.png",
        "SUSHI": "https://s2.coinmarketcap.com/static/img/coins/64x64/6758.png",
        "1INCH": "https://s2.coinmarketcap.com/static/img/coins/64x64/8104.png",
        "BAO": "https://coinmarketcap.com/currencies/bao-finance/",
        "ALPHA": "https://s2.coinmarketcap.com/static/img/coins/64x64/7232.png",
        "CREAM": "https://s2.coinmarketcap.com/static/img/coins/64x64/6193.png",
        "PICKLE": "https://s2.coinmarketcap.com/static/img/coins/64x64/7022.png",
        "RSR": "https://s2.coinmarketcap.com/static/img/coins/64x64/3964.png",
        "RUNE": "https://s2.coinmarketcap.com/static/img/coins/64x64/4157.png",
        "UMA": "https://s2.coinmarketcap.com/static/img/coins/64x64/5617.png",
        "NXM": "https://s2.coinmarketcap.com/static/img/coins/64x64/5830.png",
        "BAL": "https://s2.coinmarketcap.com/static/img/coins/64x64/5728.png",
        "BAND": "https://s2.coinmarketcap.com/static/img/coins/64x64/4679.png",
        "HEGIC": "https://s2.coinmarketcap.com/static/img/coins/64x64/6929.png",
        "MIR": "https://s2.coinmarketcap.com/static/img/coins/64x64/7857.png",
        "DPI": "https://s2.coinmarketcap.com/static/img/coins/64x64/7055.png",
        "FARM": "https://s2.coinmarketcap.com/static/img/coins/64x64/6859.png",
        "BADGER": "https://s2.coinmarketcap.com/static/img/coins/64x64/7859.png",
        "DIGG": "https://s2.coinmarketcap.com/static/img/coins/64x64/8307.png",
        "SFI": "https://s2.coinmarketcap.com/static/img/coins/64x64/7617.png",
        "AKRO": "https://s2.coinmarketcap.com/static/img/coins/64x64/4134.png",
        "BOND": "https://s2.coinmarketcap.com/static/img/coins/64x64/7440.png",
        "GRT": "https://s2.coinmarketcap.com/static/img/coins/64x64/6719.png",
        "ESD": "https://s2.coinmarketcap.com/static/img/coins/64x64/7033.png",
        "DSD": "https://s2.coinmarketcap.com/static/img/coins/64x64/8106.png",
        "FRAX": "https://s2.coinmarketcap.com/static/img/coins/64x64/6952.png",
    }

    return coinIconMap.hasOwnProperty(coinTicker) ? coinIconMap[coinTicker] : coinIconMap["???"]
}
