
export const getCoinIconURL = (coinTicker) => {
    const coinIconMap = {
        "???": "https://www.freepnglogos.com/uploads/thinking-png/thinking-speaking-emoji-draper-inc-blog-site-4.png",
        "ETH": "https://ethereum.org/static/a183661dd70e0e5c70689a0ec95ef0ba/16c7d/eth-diamond-purple.png",
        "aETH": "https://aave.com/static/media/aETH.6f2c0bbe.svg",
        "WETH": "https://svgshare.com/i/Bff.svg",
        "aWETH": "https://aave.com/static/media/aWETH.8bcd3ba4.svg",
        "USDC": "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/svg/icon/usdc.svg",
        "aUSDC": "https://aave.com/static/media/aUSDC.e260d492.svg",
        "USDT": "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/svg/icon/usdt.svg",
        "aUSDT": "https://aave.com/static/media/aUSDT.78f5faae.svg",
        "TUSD": "https://cryptologos.cc/logos/trueusd-tusd-logo.svg",
        "aTUSD":"https://aave.com/static/media/aTUSD.08592b49.svg",
        "sUSD": "https://raw.githubusercontent.com/Synthetixio/synthetix-assets/master/synths/sUSD.svg",
        "aSUSD": "https://aave.com/static/media/aSUSD.9b00ffc6.svg",
        "BUSD": "https://cryptologos.cc/logos/binance-usd-busd-logo.svg",
        "aBUSD": "https://aave.com/static/media/aBUSD.346a65d7.svg",
        "GUSD": "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/svg/icon/gusd.svg",
        "DAI": "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/svg/icon/dai.svg",
        "aDAI": "https://aave.com/static/media/aDAI.84b6c41f.svg",
        "AAVE": "https://cryptologos.cc/logos/aave-aave-logo.svg", 
        "aAAVE": "https://aave.com/static/media/aAAVE.ab13520b.svg",
        "UNI": "https://cryptologos.cc/logos/uniswap-uni-logo.svg",
        "aUNI": "https://aave.com/static/media/aUNI.81ed9562.svg",
        "YFI": "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/svg/icon/yfi.svg",
        "aYFI": "https://aave.com/static/media/aYFI.15777dd9.svg",
        "BAT": "https://cryptologos.cc/logos/basic-attention-token-bat-logo.svg",
        "aBAT": "https://aave.com/static/media/aBAT.1fe436f7.svg",
        "REN": "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/svg/icon/ren.svg",
        "ENJ": "https://cryptologos.cc/logos/enjin-coin-enj-logo.svg",
        "KNC": "https://cryptologos.cc/logos/kyber-network-knc-logo.svg",
        "aKNC": "https://aave.com/static/media/aKNC.42bcd2e3.svg",
        "REP": "https://aave.com/static/media/rep.1791e143.svg",
        "aREP": "https://aave.com/static/media/aREP.02671e96.svg",
        "LINK": "https://cryptologos.cc/logos/chainlink-link-logo.svg",
        "aLINK": "https://aave.com/static/media/aLINK.412c6589.svg",
        "MANA": "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/svg/icon/mana.svg",
        "aMANA": "https://aave.com/static/media/aMANA.f89a1098.svg",
        "MKR": "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/svg/icon/mkr.svg",
        "aMKR": "https://aave.com/static/media/aMKR.ac965178.svg",
        "SNX": "https://raw.githubusercontent.com/Synthetixio/synthetix-assets/master/snx/SNX.svg", 
        "aSNX": "https://aave.com/static/media/aSNX.3238f3e7.svg",
        "WBTC": "https://cryptologos.cc/logos/wrapped-bitcoin-wbtc-logo.svg",
        "aWBTC": "https://aave.com/static/media/aWBTC.41453c2a.svg",
        "ZRX": "https://cryptologos.cc/logos/0x-zrx-logo.svg",
        "aZRX": "https://aave.com/static/media/aZRX.9be555a9.svg",
        "CRV": "https://cryptologos.cc/logos/curve-dao-token-crv-logo.svg",
        "aCRV": "https://aave.com/static/media/aCRV.a49c7255.svg",
        "COMP": "https://s2.coinmarketcap.com/static/img/coins/64x64/5692.png",
        "SUSHI": "https://s2.coinmarketcap.com/static/img/coins/64x64/6758.png",
        "1INCH": "https://s2.coinmarketcap.com/static/img/coins/64x64/8104.png",
        "BAO": "https://coinmarketcap.com/currencies/bao-finance/",
        "ALPHA": "https://s2.coinmarketcap.com/static/img/coins/64x64/7232.png",
        "CREAM": "https://s2.coinmarketcap.com/static/img/coins/64x64/6193.png",
        "PICKLE": "https://s2.coinmarketcap.com/static/img/coins/64x64/7022.png",
        "RSR": "https://s2.coinmarketcap.com/static/img/coins/64x64/3964.png",
        "RUNE": "https://s2.coinmarketcap.com/static/img/coins/64x64/4157.png",
        "UMA": "https://s2.coinmarketcap.com/static/img/coins/64x64/5617.png",
        "NXM": "https://s2.coinmarketcap.com/static/img/coins/64x64/5830.png",
        "BAL": "https://s2.coinmarketcap.com/static/img/coins/64x64/5728.png",
        "BAND": "https://s2.coinmarketcap.com/static/img/coins/64x64/4679.png",
        "HEGIC": "https://s2.coinmarketcap.com/static/img/coins/64x64/6929.png",
        "MIR": "https://s2.coinmarketcap.com/static/img/coins/64x64/7857.png",
        "DPI": "https://s2.coinmarketcap.com/static/img/coins/64x64/7055.png",
        "FARM": "https://s2.coinmarketcap.com/static/img/coins/64x64/6859.png",
        "BADGER": "https://s2.coinmarketcap.com/static/img/coins/64x64/7859.png",
        "DIGG": "https://s2.coinmarketcap.com/static/img/coins/64x64/8307.png",
        "SFI": "https://s2.coinmarketcap.com/static/img/coins/64x64/7617.png",
        "AKRO": "https://s2.coinmarketcap.com/static/img/coins/64x64/4134.png",
        "BOND": "https://s2.coinmarketcap.com/static/img/coins/64x64/7440.png",
        "GRT": "https://s2.coinmarketcap.com/static/img/coins/64x64/6719.png",
        "ESD": "https://s2.coinmarketcap.com/static/img/coins/64x64/7033.png",
        "DSD": "https://s2.coinmarketcap.com/static/img/coins/64x64/8106.png",
        "FRAX": "https://s2.coinmarketcap.com/static/img/coins/64x64/6952.png",
    }

    return coinIconMap.hasOwnProperty(coinTicker) ? coinIconMap[coinTicker] : coinIconMap["???"]
}
